### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fgaz** [bcampbell/impy#1]
As far as I can see, evilpixie requires an unreleased impy version. I'd like to upgrade the evilipxie NixOS package, and a new impy release would make it easier.

**Comment by bcampbell** [comment]
I just added a v0.2 tag+release. Probably obvious, but I switched both evilpixie and impy over to meson (from qmake and cmake respectively).
Impy uses SDL2 for one of the examples, but it's absolutely not a requirement, and should build fine without it.

**Comment by fgaz** [comment]
Noted, thank you
